/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function keepaliveBloxroute(apiKey: string, apiUrl: string): Promise<void>

export declare function keepaliveNodeme(apiUrl: string): Promise<void>

export declare function keepaliveSlot(apiUrl: string, authKey: string): Promise<void>

export declare function keepaliveTemporal(apiUrl: string): Promise<void>

export interface SolAccountStruct {
  publicKey: string
  seed: string
}

export declare function swap(param: SwapParam4Node): Promise<Array<string>>

export interface SwapParam4Node {
  connection: string
  connectionBrand: string
  secretKey: string
  amountIn: string
  amountOut: string
  fixedSide: string
  targetPool: string
  tokenIn: string
  tokenOut: string
  decimalsIn: string
  decimalsOut: string
  slippageAmount: string
  computeUnit?: string
  computePrice?: string
  jitoComputePrice?: string
  bloxrouteComputePrice?: string
  temporalComputePrice?: string
  nextblockComputePrice?: string
  slot0TradeComputePrice?: string
  nodemeComputePrice?: string
  blockEngineLocate?: string
  blockEngineUrl?: string
  bundleBribe?: string
  jitoBribe?: string
  bloxrouteBundleBribe?: string
  temporalBundleBribe?: string
  nextblockBundleBribe?: string
  slot0TradeBundleBribe?: string
  nodemeBundleBribe?: string
  bundleAmountOut?: string
  buyOnce?: boolean
  maxBlockNumber?: string
  tokenBalance?: string
  tokenMint?: string
  marketId?: string
  skipRetry?: boolean
  groupId?: string
  group?: string
  tradeTimes?: string
  recentBlockHash?: string
  jitoRecentBlockHash?: string
  bloxrouteRecentBlockHash?: string
  temporalRecentBlockHash?: string
  nextblockRecentBlockHash?: string
  slot0TradeRecentBlockHash?: string
  nodemeRecentBlockHash?: string
  solAccount?: SolAccountStruct
  coinAccount?: string
  maxAmountOut?: string
  bundleType?: string
  remainTokenBalance?: string
  blockNumber?: string
  simulateBundleBribe?: string
  secondBlockBundleBribe?: string
  landBundleBribe?: string
  calculateAmountOut?: boolean
  trackTokenAccount?: string
  trackAmountIn?: string
  trackSlippage?: string
  trackMaxAllowBuy?: string
  trackTokenBalance?: string
  snipeRaydiumSolReserve?: string
  sendNormalTrade?: string
  tradeManualLocalRpc?: string
  antiMev?: string
  creatorVault?: string
}
